language: generic
branches:
  only:
    - src

before_install:
  - sudo apt-get update -qq

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.40.1/hugo_0.40.1_Linux-64bit.deb
  - sudo dpkg -i *.deb

script:
  - hugo

deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  keep-history: true
  target-branch: master
  github-token: $GITHUB_TOKEN
  on:
    branch: src
