languageCode = "en-us"
title = "prakashsurya.github.io"
baseurl = "https://prakashsurya.github.io/"

[[menu.main]]
  name = "Home"
  weight = 0
  url = "/"
[[menu.main]]
  name = "Posts"
  weight = 1
  url = "/post/"
