languageCode = "en-us"
title = "www.prakashsurya.com"
baseurl = "https://www.prakashsurya.com/"

googleAnalytics = "UA-91378771-1"

[[menu.main]]
  name = "Home"
  weight = 0
  url = "/"
[[menu.main]]
  name = "Posts"
  weight = 1
  url = "/post/"
